### ISSUE TITLE
Device names not surrounded with quotes

### ISSUE THREAD

**Issue by DavidGriffith** [wd5gnr/qtl866#1]
Trying to manipulate a chip using the profile of "at29c256 @DIP28" fails with "Unknown device".  Poking around with the underlying minipro program, I see a troubling snag:  If you don't surround the device name with quotes and the device name contains a space, minipro won't get the whole name.  qtl866 is apparently not doing this.

**Comment by enkore** [comment]
Fixed in 222242c4c
